// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"SAN_ExtendedEventPage","status":true,"description":"拡張イベントページ制御 ver1.01\r\n任意のイベントページの出現条件と出現時処理を設定します。","parameters":{}}
];
